# Generated by Django 4.2.7 on 2023-11-24 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('occupation', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('age', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('annual_income', models.FloatField()),
                ('monthly_inhand_salary', models.FloatField()),
                ('num_bank_accounts', models.FloatField()),
                ('num_credit_card', models.FloatField()),
                ('num_of_loan', models.FloatField()),
                ('num_credit_inquiries', models.FloatField()),
                ('credit_history_age', models.FloatField()),
                ('amount_invested_monthly', models.FloatField()),
                ('payment_behaviour', models.CharField(max_length=50)),
                ('monthly_balance', models.FloatField()),
                ('password', models.IntegerField()),
                ('access_token', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.users'),
        ),
    ]
