# Generated by Django 4.2.7 on 2023-11-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_alter_history_id_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='amount_invested_monthly',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='annual_income',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='credit_history_age',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='monthly_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='monthly_inhand_salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='num_bank_accounts',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='num_credit_card',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='num_credit_inquiries',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='num_of_loan',
            field=models.FloatField(null=True),
        ),
    ]
