# Generated by Django 4.2.7 on 2023-11-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='credit_history_age',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(),
        ),
    ]
