# Generated by Django 4.2.7 on 2023-11-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0011_alter_history_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='credit_score',
        ),
        migrations.AddField(
            model_name='history',
            name='course',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='credit_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='credit_period',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='payment_per_month',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='pure_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='pure_currency_name',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
