# Generated by Django 4.2.7 on 2023-11-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_alter_users_age_alter_users_amount_invested_monthly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
