# Generated by Django 4.2.7 on 2023-11-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_alter_users_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
