# Generated by Django 4.2.7 on 2023-11-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_remove_users_credit_history_age_history_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.BinaryField(),
        ),
    ]
